DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    view_users BOOLEAN NOT NULL DEFAULT FALSE,
    update_user BOOLEAN NOT NULL DEFAULT FALSE
);
